backend:
  name: github
  repo: DomtronVox/StaticFarmSite # Path to your Github repository
  branch: master # Branch to update

media_folder: src/files/images/
public_folder: images/

collections: # A list of collections the CMS should be able to edit
  - name: "main_page"
    label: "Main Pages"
    folder: "src/documents/main_pages"
    create: "true"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Navigation Bar Text", name: "navTitle", widget: "string"}
      - {label: "Navigation bar priority (lower=farther left)", name: "navPriority", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "MainPage"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.html"}
    meta: #no clue what meta does. Didn't work as I was expecting.
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"} 
      
  - name: "sub_page"
    label: "Sub Pages"
    folder: "src/documents/sub_pages"
    create: "true"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Navigation Bar Text", name: "navTitle", widget: "string"}
      - {label: "Which Main Page to sort navigation button under.", name: "navNest", widget: "relation", collection: "main_page", searchFields: ["title", "navTitle"], valueField: "title"}
      - {label: "Navigation bar priority (lower=farther up)", name: "navPriority", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "SubPage"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.html"}
    meta: #no clue what meta does. Didn't work as I was expecting.
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "kidding_schedule"
    label: "Kidding Schedule"
    folder: "src/documents/kidding_schedule"
    create: "false"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", default:"Kidding Schedule"}
      - {label: "Navigation Bar Text", name: "navTitle", widget: "string"}
      - {label: "Navigation bar priority (lower=farther up)", name: "navPriority", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Kidding Table Title", name: "tableTitle", widget: "string"}

      - label: "Kidding Table"
        name: "kidding_table"
        required: false,
        widget: "list"
        fields:
            - {required: false, label: "Dam", name: "dam", widget: "relation", collection: "goats", searchFields: ["title", "nickname"], valueField: "title"}
            - {required: false, label: "Selling Dam?", name: "sellingDam", widget: "boolean"}
            - {required: false, label: "Show Dam LA Score?", name: "showDamLAScore", widget: "boolean"}
            - {required: false, label: "Sire", name: "sire", widget: "relation", collection: "goats", searchFields: ["title", "nickname"], valueField: "title"}
            - {required: false, label: "Show Sire LA Score?", name: "showSireLAScore", widget: "boolean"}
            - {required: false, label: "Pregnancy Confirmed?", name: "confirmation", widget: "boolean"}
            - {required: false, label: "Due Date", name: "dueDate", widget: "string"}
            - {required: false, label: "Genetic Notes", name: "geneticNotes", widget: "string"}
            - label: "Notes List"
              name: "notes_list"
              required: false,
              widget: "list"
              fields: 
                  - {required: false, label: "Note", name: "note", widget: "string"} 

      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "MainPage"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "kidding_schedule.html"}
    meta: #no clue what meta does. Didn't work as I was expecting.
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}



  - name: "goats" 
    label: "Goat Pages"
    folder: "src/documents/Goats" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {required: false,  label: "Earned Titles", name: "titlesEarned", widget: "string"}
      - {required: true,  label: "Full Goat Name", name: "title", widget: "string"}
      - {required: false,  label: "Milk Star", name: "milkStar", widget: "string"}
      - {required: true,  label: "Nickname", name: "nickname", widget: "string"}
      - {required: false,  label: "Gender", name: "gender", widget: "select", options: ["Buck", "Senior Doe", "Junior Doe"]}
      - {required: false, label: "For Sale?", name: "forSale", widget: "boolean"}
      - {required: false, label: "LA Score", name: "la_score", widget: "string"}
      - {required: false, label: "Birth Date", name: "birth_date", widget: "string", default: "" }
      - {required: false, label: "Description", name: "body", widget: "markdown"}

      - {required: false, label: "ADGA Registration Number", name: "adga_num", widget: "string"}
      - {required: false, label: "AGS Registration Number", name: "ags_num", widget: "string"}

      - {required: false, label: "Blue Eyes", name: "blue_eyes", widget: "boolean"}
      - {required: false, label: "Polled", name: "polled", widget: "boolean"}
      - {required: false, label: "Moonspots", name: "moonspots", widget: "boolean"}
      - {required: false, label: "Is it a Reference Goat", name: "reference", widget: "select", options: ["no", "yes"], default:"no"}

      - label: "Sire"
        name: "sireNameData"
        widget: "object"
        fields:
            - {required: false,  label: "Earned Titles", name: "titles", widget: "string"}
            - {required: false,  label: "Name", name: "name", widget: "string"}
            - {required: false,  label: "Name Postfix", name: "postfix", widget: "string"}

      - label: "Dam"
        name: "damNameData"
        widget: "object"
        fields:
            - {required: false,  label: "Earned Titles", name: "titles", widget: "string"}
            - {required: false,  label: "Name", name: "name", widget: "string"}
            - {required: false,  label: "Name Postfix", name: "postfix", widget: "string"}

      - label: "Sire's Sire"
        name: "sire_sireNameData"
        widget: "object"
        required: false
        fields:
            - {required: false,  label: "Earned Titles", name: "titles", widget: "string"}
            - {required: false,  label: "Name", name: "name", widget: "string"}
            - {required: false,  label: "Name Postfix", name: "postfix", widget: "string"}

      - label: "Sire's Dam"
        name: "sire_damNameData"
        widget: "object"
        required: false
        fields:
            - {required: false,  label: "Earned Titles", name: "titles", widget: "string"}
            - {required: false,  label: "Name", name: "name", widget: "string"}
            - {required: false,  label: "Name Postfix", name: "postfix", widget: "string"}

      - label: "Dam's Sire"
        name: "dam_sireNameData"
        widget: "object"
        required: false
        fields:
            - {required: false,  label: "Earned Titles", name: "titles", widget: "string"}
            - {required: false,  label: "Name", name: "name", widget: "string"}
            - {required: false,  label: "Name Postfix", name: "postfix", widget: "string"}

      - label: "Dam's Dam"
        name: "dam_damNameData"
        widget: "object"
        required: false
        fields:
            - {required: false,  label: "Earned Titles", name: "titles", widget: "string"}
            - {required: false,  label: "Name", name: "name", widget: "string"}
            - {required: false,  label: "Name Postfix", name: "postfix", widget: "string"}


      - {required: false, label: "Pedigree Picture", name: "pedigree_picture", widget: "image"}

      - {required: false, label: "Side Picture", name: "side_picture", widget: "image"}
      - {required: false, label: "Back/Udder Picture", name: "back_picture", widget: "image"}
#      - {required: false, label: "2nd Side Picture", name: "side2_picture", widget: "image"}
#      - {required: false, label: "Front Picture", name: "front_picture", widget: "image"}
#      - {required: false, label: "Highlight Picture", name: "highlight_picture", widget: "image"}

      - label: "Milk Records"
        name: "milk_records"
        required: false,
        widget: "list"
        fields:
            - {required: false, label: "Year", name: "milkRecordYear", widget: "string"}
            - {required: false, label: "DIM", name: "milkRecordDIM", widget: "string"}
            - {required: false, label: "DIM Volume (LBS)", name: "milkRecordVolume", widget: "string"}
            - {required: false, label: "Fat (%)", name: "milkRecordFat", widget: "string"}
            - {required: false, label: "Fat (LBS)", name: "milkRecordFatLBS", widget: "string"}
            - {required: false, label: "Protein (%)", name: "milkRecordProtein", widget: "string"}
            - {required: false, label: "Protein (LBS)", name: "milkRecordProteinLBS", widget: "string"}
      - {required: false, label: "Milk Record Comments", name: "milkRecordComments", widget: "string"}
            

      - label: "Gallery"
        name: "galleryImages"
        required: false
        widget: "list"
        fields:
            - {required: false, label: "Image", name: "image", widget: "image"}
            - {required: false, label: "Caption", name: "caption", widget: "string"}

#      - {required: false, label: "Sire Picture 1", name: "sire_picture1", widget: "image"}
#      - {required: false, label: "Sire Picture 2", name: "sire_picture2", widget: "image"}
#      - {required: false, label: "Dam Picture 1", name: "dam_picture1", widget: "image"}
#      - {required: false, label: "Dam Picture 2", name: "dam_picture2", widget: "image"}
      - label: "Kidding History"
        name: "kiddingHistory"
        required: false
        widget: "list"
        fields:
            - {required: false, label: "Date", name: "bredDate", widget: "string"}
            - {required: false, label: "Bred To", name: "breeder", widget: "string"}
            - {required: false, label: "Doelings", name: "doeCount", widget: "number"}
            - {required: false, label: "Bucklings", name: "buckCount", widget: "number"}
            - {required: false, label: "Comments", name: "comments", widget: "string"}
     
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "goatpage.html"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "Goats"}      

