backend:
  name: github
  repo: DomtronVox/StaticFarmSite # Path to your Github repository
  branch: master # Branch to update

media_folder: src/files/images/
public_folder: images/

collections: # A list of collections the CMS should be able to edit
  - name: "main_page"
    label: "Main Pages"
    folder: "src/documents/main_pages"
    create: "true"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Navigation Bar Text", name: "navTitle", widget: "string"}
      - {label: "Navigation bar priority (lower=farther left)", name: "navPriority", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "MainPage"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.html"}
    meta: #no clue what meta does. Didn't work as I was expecting.
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"} 
      
  - name: "sub_page"
    label: "Sub Pages"
    folder: "src/documents/sub_pages"
    create: "true"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Navigation Bar Text", name: "navTitle", widget: "string"}
      - {label: "Which Main Page to sort navigation button under.", name: "navNest", widget: "relation", collection: "main_page", searchFields: ["title", "navTitle"], valueField: "title"}
      - {label: "Navigation bar priority (lower=farther up)", name: "navPriority", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "SubPage"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.html"}
    meta: #no clue what meta does. Didn't work as I was expecting.
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "goats" 
    label: "Goat Pages"
    folder: "src/documents/Goats" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {required: true,  label: "Full Goat Name", name: "title", widget: "string"}
      - {required: true,  label: "Nickname", name: "nickname", widget: "string"}
      - {required: false, label: "LA Score", name: "la_score", widget: "string"}
      - {required: true,  label: "Gender", name: "gender", widget: "select", options: ["male", "female"]}
      - {required: false,  label: "Birth Date", name: "birth_date", widget: "datetime"}
      - {required: false, label: "Description", name: "body", widget: "markdown"}

      - {required: false, label: "ADGA Registration Number", name: "adga_num", widget: "string"}
      - {required: false, label: "AGS Registration Number", name: "ags_num", widget: "string"}
      - {required: false, label: "Milk Records", name: "milk_records", widget: "text"}

      - {required: false, label: "Extra Info", name: "extra_info", widget: "markdown"}
      - {required: false, label: "Blue Eyes", name: "blue_eyes", widget: "select", options: ["no", "yes"], default:"no"}
      - {required: false, label: "Polled", name: "polled", widget: "select", options: ["no", "yes"], defualt:"no"}
      - {required: true, label: "Is it a Reference Goat", name: "reference", widget: "select", options: ["no", "yes"], default:"no"}

      - {required: true,  label: "Sire", name: "sire", widget: "string"}
      - {required: true,  label: "Dam", name: "dam", widget: "string"}

      - {required: false,  label: "Sire's Sire", name: "sire_sire", widget: "string"}
      - {required: false,  label: "Sire's Dam", name: "sire_dam", widget: "string"}

      - {required: false,  label: "Dam's Sire", name: "dam_sire", widget: "string"}
      - {required: false,  label: "Dam's Dam", name: "dam_dam", widget: "string"}

      - {required: false, label: "Pdigree Picture", name: "pedigree_picture", widget: "image"}

      - {required: false, label: "Side Picture", name: "side_picture", widget: "image"}
      - {required: false, label: "2nd Side Picture", name: "side2_picture", widget: "image"}
      - {required: false, label: "Front Picture", name: "front_picture", widget: "image"}
      - {required: false, label: "Back/Udder Picture", name: "back_picture", widget: "image"}
      - {required: false, label: "Highlight Picture", name: "highlight_picture", widget: "image"}

      - {required: false, label: "Sire Picture 1", name: "sire_picture1", widget: "image"}
      - {required: false, label: "Sire Picture 2", name: "sire_picture2", widget: "image"}
      - {required: false, label: "Dam Picture 1", name: "dam_picture1", widget: "image"}
      - {required: false, label: "Dam Picture 2", name: "dam_picture2", widget: "image"}

      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "goatpage.html"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "Goats"}      

